<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>97d929aa-1bab-44a3-8b77-785d2f0c7b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='room-details']/div[2]/div/div[2]/div/div/div[3]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//from.bookit-qa6.com/review.php?fd=2019-05-01&amp;td=2019-05-08&amp;rm=1&amp;ap1=2&amp;mp1=1&amp;ar1m1=3&amp;areaId=1703&amp;adid=undefined&amp;pt=h&amp;tripType=hotel&amp;hotelTo=Cheese+City%2C+IL%2C+US&amp;tl=CMI&amp;fromLocation=New+York+-+All+Airports%2C+NY%2C+US+%28NYC%29&amp;fl=NYC&amp;hfd=2019-05-01&amp;htd=2019-05-08&amp;hotelId=CH10111&amp;hotelVendorId=BT&amp;hotelUniqueId=9533647&amp;xmlConnectionId=12&amp;debug=1&amp;marketId=27315&amp;locationId=CMI&amp;roomId=2BEDTESTSTE&amp;rch=a3edf197dbff9343eca6220577c8eda1&amp;rci=CHEESEBASE&amp;rcid=2751085&amp;sp=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-phone</name>
      <type>Main</type>
      <value>1-888-782-9722</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-searchid</name>
      <type>Main</type>
      <value>41073850</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trip-type</name>
      <type>Main</type>
      <value>h</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-lg btn-bookit mt5 select-button no-fees  at-details-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-room-id</name>
      <type>Main</type>
      <value>2392385490</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        					Select
        				</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;room-details&quot;)/div[@class=&quot;bottom-content data-box room mt10&quot;]/div[@class=&quot;row no-gutter&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;rate-info one-rate&quot;]/div[@class=&quot;row rate-type&quot;]/div[@class=&quot;col-sm-3 col-sm-offset-5 col-lg-offset-4&quot;]/div[@class=&quot;btn-box&quot;]/a[@class=&quot;btn btn-block btn-lg btn-bookit mt5 select-button no-fees  at-details-select&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='room-details']/div[2]/div/div[2]/div/div/div[3]/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[4]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100'])[12]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>//a[contains(@href, '//from.bookit-qa6.com/review.php?fd=2019-05-01&amp;td=2019-05-08&amp;rm=1&amp;ap1=2&amp;mp1=1&amp;ar1m1=3&amp;areaId=1703&amp;adid=undefined&amp;pt=h&amp;tripType=hotel&amp;hotelTo=Cheese+City%2C+IL%2C+US&amp;tl=CMI&amp;fromLocation=New+York+-+All+Airports%2C+NY%2C+US+%28NYC%29&amp;fl=NYC&amp;hfd=2019-05-01&amp;htd=2019-05-08&amp;hotelId=CH10111&amp;hotelVendorId=BT&amp;hotelUniqueId=9533647&amp;xmlConnectionId=12&amp;debug=1&amp;marketId=27315&amp;locationId=CMI&amp;roomId=2BEDTESTSTE&amp;rch=a3edf197dbff9343eca6220577c8eda1&amp;rci=CHEESEBASE&amp;rcid=2751085&amp;sp=100')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div/div/div[3]/div/a</value>
   </webElementXpaths>
</WebElementEntity>
